export enum TipoParametrica {
    TIPO_CONSULTA='TIPO_CONSULTA',
    TIPO_DOCUMENTO='TIPO_DOCUMENTO',
    TIPO_USUARIO='TIPO_USUARIO',
    TIPO_SERVICIO='TIPO_SERVICIO',
    TIPO_CIUDAD='TIPO_CIUDAD',
    TIPO_GENERO='TIPO_GENERO',
    ESTADO_CUENTA='ESTADO_CUENTA',
    TIPO_CUENTA='TIPO_CUENTA',
  }
