export const adm = {
    UN_DIA: 24 * 60 * 60 * 1000,
    TIPO_USUARIO_SUPERADMIN: 'USP',
    TIPO_USUARIO_ADMIN: 'UADM',
    TIPO_USUARIO_MEDICO: 'UMED',
    TIPO_USUARIO_ASISTENTE: 'UASIS',
    TIPO_USUARIO_EXTERNO: 'UEXT',

    CITA_ESTADO_RESERVA:'RES',
    CITA_TIPO_CONSULTA:'CON',

    NUMERO_DECIMALES:2,
    NUMERO_DECIMALES_ICE:5,
    PIPE_NUMERO_DECIMALES:'1.2-2',
    PIPE_FECHA:'dd/MM/yyyy HH:mm',
    SEGUNDOS_GPS:5,
  };
