export const adm = {
    UN_DIA: 24 * 60 * 60 * 1000,
    TIPO_USUARIO_SUPERADMIN: 'USP',
    TIPO_USUARIO_ADMIN: 'UADM',
    TIPO_USUARIO_PROFESIONAL: 'UPROF',
    TIPO_USUARIO_ASISTENTE: 'UASIS',
    TIPO_USUARIO_EXTERNO: 'UEXT',

    TIPO_DOC_CI: 'CI',

    TIPO_PRODUCTO_SERVICIO: 'SRV',
    TIPO_PRODUCTO_PRODUCTO: 'PROD',
    TIPO_PRODUCTO_PRODUCTO_INVENTARIO: 'PRODI',

    CITA_ESTADO_RESERVA:'RES',
    CITA_ESTADO_EN_ESPERA:'ESP',
    CITA_ESTADO_INICIADA:'INI',
    CITA_ESTADO_CONFIRMADA:'CONF',
    CITA_ESTADO_INASISTENCIA:'INASI',


    CONSULTA_TIPO_CONSULTA:'CON',
    CONSULTA_TIPO_RECONSULTA:'RCON',

    ESTADO_CUENTA_ACTIVO: 'CACT',
    ESTADO_CUENTA_COBRADA: 'CCOB',
    ESTADO_CUENTA_CREDITO_POR_PAGAR: 'CCXP',
    ESTADO_CUENTA_CREDITO_PAGADO: 'CCP',
    ESTADO_CUENTA_REVERTIDA: 'CREV',

    ESTADO_TURNO_ABIERTO: 'ATO',
    ESTADO_TURNO_CERRADO: 'CDO',

    TIPO_CUENTA_CONTADO: 'CCONT',
    TIPO_CUENTA_CREDITO: 'CCRED',

    TIPO_DESCUENTO_TOTAL: 'DT',
    TIPO_DESCUENTO_MONTO: 'DM',
    TIPO_DESCUENTO_PORCENTAJE: 'DP',

    NUMERO_DECIMALES:2,
    NUMERO_DECIMALES_ICE:5,
    PIPE_NUMERO_DECIMALES:'1.2-2',
    PIPE_FECHA:'dd/MM/yyyy HH:mm',
    SEGUNDOS_GPS:5,


    TIPO_PARAMAETRICA_SFE_TIPO_DOCUMENTO: 'TIPO_DOCUMENTO',
    TIPO_PARAMAETRICA_SFE_TIPO_EVENTO: 'TIPO_EVENTO',
    TIPO_PARAMAETRICA_SFE_TIPO_METODO_PAGO: 'TIPO_METODO_PAGO',
    TIPO_PARAMAETRICA_SFE_TIPO_MONEDA: 'TIPO_MONEDA',
    TIPO_PARAMAETRICA_SFE_TIPO_PUNTO_VENTA: 'TIPO_PUNTO_VENTA',
    TIPO_PARAMAETRICA_SFE_TIPO_UNIDAD_MEDIDA: 'TIPO_UNIDAD_MEDIDA',
    TIPO_PARAMAETRICA_SFE_TIPO_MOTIVO_ANULACION: 'TIPO_MOTIVO_ANULACION',


    CODIGO_TIPO_PAGO_EFECTIVO: 1,
    CODIGO_TIPO_PAGO_TARJETA: 2,
    CODIGO_TIPO_PAGO_POSTERIOR: 6,
    CODIGO_TIPO_PAGO_DEPOSITO_EN_CUENTA: 8,
    CODIGO_TIPO_PAGO_ONLINE: 33,

    CODIGO_PAIS_BOLIVIA: 22,

    CODIGO_TIPO_MONEDA_BOLIVIANO: 1,
    TIPO_DE_CAMBIO_BOLIVIANO:1,


    ESTADO_FACTURA_PENDIENTE: 901,
    ESTADO_FACTURA_RECHAZADA: 902,
    ESTADO_FACTURA_VALIDADO: 908,
    ESTADO_FACTURA_ANULADO: 905,
    ESTADO_FACTURA_OBSERVADO: 904,
    ESTADO_FACTURA_REVERTIDA: 907,

  };
