// Generated by https://quicktype.io
export interface Cuenta {
    correlativo?:      number;

    estadoCuenta?:        string;
    fecha?:              string;
    id:                 number;
    //cliente?:               any;
    idCliente?:          number;
    cliente?:      string;
    codigoCliente?:      string;
    telefonoCliente?:      string;

    codigoEstadoCuenta:      string;
    idSucursal:         number;
    numeroSucursal?:         number;
    codigoTipoCuenta:        string;

    tipoCuenta?:          string;
    subtotal:     number;
    descuentoAdicional: number;
    total:              number;

    saldo?:              number;
    itemsEliminados?:    number[]|null;
    detalle?:            CuentaDetalle[];
    usuario?:              string;

    codigoEstadoFactura?:              number;
    estadoFactura?:              string;
    cufFactura?:              string;
    numeroFactura?:              number;
}

export interface CuentaDetalle {
    cantidad:        number;
    codigoServicio?:  string;
    descuento:       number;
    id?:              number;
    idServicio?:      number;
    codigoTipoDescuento?: string;
    valorDescuento?:  number;
    codigoTipoServicio?:  string;
    idCuenta?:         number;
    precio:          number;
    servicio?:        string;
    subtotal:        number;
    total:           number;
    codigo?:     string;
    descripcionAdicional?:     string;
}

